### ISSUE TITLE
View logs in Openshift not working

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis-react#398] opened 2019-06-03 19:12 UTC
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Documentation issue or request
</code></pre>

View logs gives me an error:
![image](https://user-images.githubusercontent.com/674767/58827843-069d0d80-8612-11e9-9560-d17dce9f37ff.png)

**Comment by paoloantinori** [comment] 2019-06-04 14:49
Duplicate of #360

**Closed** 2019-06-04 14:50 UTC
